server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "your-256-bit-secret-your-256-bit-secret"
