server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/users/**
        - id: workout-service
          uri: http://workout-service:8083
          predicates:
            - Path=/workouts/**
        - id: payment-service
          uri: http://payment-service:8084
          predicates:
            - Path=/payments/**
        - id: notification-service
          uri: http://notification-service:8085
          predicates:
            - Path=/notifications/**
        - id: analytics-service
          uri: http://analytics-service:8086
          predicates:
            - Path=/analytics/**
