server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/payment_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672

payment:
  providers:
    stripe: "sk_test_..."
    yookassa: "your_yookassa_key"
