server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
