server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/analytics_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672

monitoring:
  prometheus:
    enabled: true
  grafana:
    dashboards: true
